"""Mutation checks for the QAT test suite (Batch #2 audit + Batch #2.1 / #2.2 policies).

Each entry temporarily edits one source file, runs the relevant tests with -x and
restores the file in a ``finally`` block. CAUGHT = the suite fails on the mutant
(good); SURVIVED = false confidence (bad). Run from the repository root; keep a
backup of ``src`` if you interrupt it.

    python artifacts/verification/audit_batch2/mutate_leakage_and_defects.py [label-substring ...]
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "tools"))
import mutation_harness  # noqa: E402
PY = sys.executable
TESTS = ["tests/test_research.py", "tests/test_ui.py", "tests/test_audit_batch2.py", "tests/test_policy_batch2_1.py",
         "tests/test_exit_policy_batch2_2.py", "tests/test_realdata_unit.py", "tests/test_realdata_integration.py",
         "tests/test_mutation_harness.py", "tests/test_protocol.py", "tests/test_validity.py", "tests/test_intraday.py", "tests/test_protocol_v2.py", "tests/test_protocol_v2_run.py", "tests/test_holdout_eval.py", "tests/test_protocol_v2_closure.py"]
RD_UNIT = ["tests/test_realdata_unit.py"]
RD_INT = ["tests/test_realdata_integration.py"]
RD_ALL = RD_UNIT + RD_INT
PROTO = ["tests/test_protocol.py"]
VALID = ["tests/test_validity.py"]
INTRA = ["tests/test_intraday.py"]
PV2 = ["tests/test_protocol_v2.py"]
RUN2 = ["tests/test_protocol_v2_run.py"]
HOLD = ["tests/test_holdout_eval.py"]
CLOSE = ["tests/test_protocol_v2_closure.py"]
OPSC = ["tests/test_ops_core.py"]
OPSS = ["tests/test_ops_service.py"]
BRK = ["tests/test_brokerage.py"]
MUTS = [
    ("engine history window +1 bar", "src/qat/research/backtest.py",
     "History(bars, t + 1)", "History(bars, min(t + 2, len(bars)))"),
    ("engine trade_end slice +1 bar", "src/qat/research/backtest.py",
     "dataset.bars[: config.trade_end]", "dataset.bars[: config.trade_end + 1]"),
    ("empirical alpha uses close[t+1]", "src/qat/research/strategies.py",
     "if i + horizon <= t and i + 1 <= t", "if i + horizon <= t + 1 and i + 1 <= t + 1"),
    ("calibration window leaks into test (+50 bars)", "src/qat/research/walkforward.py",
     "cfg = replace(base, trade_start=train[0], trade_end=train[1])",
     "cfg = replace(base, trade_start=train[0], trade_end=train[1] + 50)"),
    ("OOS window starts inside train", "src/qat/research/walkforward.py",
     'cfg = replace(config.base, trade_start=fold["test"][0], trade_end=fold["test"][1])',
     'cfg = replace(config.base, trade_start=fold["test"][0] - 20, trade_end=fold["test"][1])'),
    ("fold test range overlaps lockbox", "src/qat/research/walkforward.py",
     "usable = n_bars - self.lockbox_bars", "usable = n_bars - self.lockbox_bars + 30"),
    ("fill at same-bar close instead of next open", "src/qat/research/backtest.py",
     "fill = broker.simulate_fill(order_id, bar.open)", "fill = broker.simulate_fill(order_id, bar.close)"),
    ("strategy state not reset between runs (D7)", "src/qat/research/backtest.py",
     "strategy.reset()", "pass"),
    ("lockbox exact-range keying (D8)", "src/qat/research/walkforward.py",
     "previous = _overlapping_lockbox_uses(registry, dataset.data_version, lo, hi)",
     "previous = registry.get(key, [])"),
    ("drawdown baseline fail-open (D4)", "src/qat/risk/gate.py",
     "if self.max_drawdown is not None and not (self._peak_equity and self._peak_equity > 0):", "if False:"),
    ("UI session never observes equity (D4)", "src/qat/ui/service.py",
     "self.stack.risk.observe_equity(val.total_base)", "pass"),
    ("UI session never resets daily baseline (D5)", "src/qat/ui/service.py",
     "                self.stack.risk.start_new_day()\n                self._prev_day = bar.ts.date()",
     "                self._prev_day = bar.ts.date()"),
    ("reconcile ignores NaN (D1)", "src/qat/portfolio/reconciliation.py",
     "if not math.isfinite(internal) or (broker_qty is not None and not math.isfinite(broker_qty)):", "if False:"),
    ("overlapping bars accepted (D6)", "src/qat/data/validation.py",
     "if delta < min_step:", "if False:"),
    ("proposal id from cache size (D9)", "src/qat/ui/service.py",
     "self._request_seq + 1:05d", "len(self.requests) + 1:05d"),
    ("host header not checked (D10)", "src/qat/ui/server.py",
     'if _hostname(self.headers.get("Host", "")) not in LOOPBACK_HOSTS:', "if False:"),
    ("Net cost: tax not scaled by cost multiplier", "src/qat/research/backtest.py",
     "market: CostModel(**{k: v * multiplier for k, v in asdict(model).items()})",
     "market: CostModel(**{k: (v if k == 'tax_rate_sell' else v * multiplier) for k, v in asdict(model).items()})"),
    # ---- Batch #2.1 policies
    ("OD-01 exemption also covers BUY", "src/qat/core/exposure.py",
     "if quantity > _EPS and proposal.side is Side.SELL:", "if quantity > _EPS:"),
    ("OD-01 exemption ignores the position bound (flip)", "src/qat/core/exposure.py",
     "return proposal.quantity <= limit + _EPS", "return True"),
    ("OD-01 exemption without a position", "src/qat/core/exposure.py",
     "    if ledger is None:\n        return False\n    position",
     "    if ledger is None:\n        return proposal.side is Side.SELL\n    position"),
    ("OD-01 exemption uses total not available quantity", "src/qat/core/exposure.py",
     "limit = position.available_quantity", "limit = position.quantity"),
    ("OD-01 every SELL exempt", "src/qat/cost/engine.py",
     "if self.reduces_exposure(proposal):", "if proposal.side is Side.SELL:"),
    ("OD-02 core default allow-all", "src/qat/compliance/gate.py",
     "DEFAULT_UNRESTRICTED_UNIVERSE = False", "DEFAULT_UNRESTRICTED_UNIVERSE = True"),
    ("OD-02 no-allowlist silent PASS", "src/qat/compliance/gate.py",
     "            status = GateStatus.UNKNOWN\n            reasons.append(\"tradable_universe_not_configured\")",
     "            reasons.append(\"universe:silent\")"),
    ("OD-02 research run uses allow-all", "src/qat/research/backtest.py",
     'compliance_kwargs={"tradable_symbols": {symbol}, "unrestricted_universe": False,',
     'compliance_kwargs={"tradable_symbols": None, "unrestricted_universe": True,'),
    ("OD-02 UI session allow-all when no allowlist", "src/qat/ui/service.py",
     '"unrestricted_universe": False,\n                "universe_label": "paper_allowlist",',
     '"unrestricted_universe": True,\n                "universe_label": "paper_allowlist",'),
    ("OD-02 research symbol leaks into paper allowlist", "src/qat/ui/service.py",
     '"tradable_symbols": (set(settings["paper_universe"])',
     '"tradable_symbols": (set(settings["paper_universe"]) | {self.meta.symbol}'),
    ("OD-03 buffer changed to 3%", "src/qat/research/backtest.py",
     "reservation_buffer_pct: float = 0.02", "reservation_buffer_pct: float = 0.03"),
    # ---- Batch #2.2 risk-reducing exit hierarchy
    ("EXIT Kill Switch lets a reducing SELL through", "src/qat/risk/gate.py",
     "        if self.kill_switch:\n            return GateDecision(GateStatus.BLOCK, (\"kill_switch\",))",
     "        if self.kill_switch and not reduces_exposure(self.ledger, proposal):\n            return GateDecision(GateStatus.BLOCK, (\"kill_switch\",))"),
    ("EXIT Daily Loss still blocks a reducing SELL", "src/qat/risk/gate.py",
     "                if relax:\n                    notes.append(\"exit_allowed:daily_loss_limit\")",
     "                if False:\n                    notes.append(\"exit_allowed:daily_loss_limit\")"),
    ("EXIT Drawdown still blocks a reducing SELL", "src/qat/risk/gate.py",
     "                if relax:\n                    notes.append(\"exit_allowed:max_drawdown\")",
     "                if False:\n                    notes.append(\"exit_allowed:max_drawdown\")"),
    ("EXIT absolute exposure still blocks a reducing SELL", "src/qat/risk/gate.py",
     "if relax:  # a reducing SELL can only lower exposure", "if False:  # a reducing SELL can only lower exposure"),
    ("EXIT drawdown UNKNOWN baseline relaxed for exits", "src/qat/risk/gate.py",
     "if self.max_drawdown is not None and not (self._peak_equity and self._peak_equity > 0):",
     "if self.max_drawdown is not None and not relax and not (self._peak_equity and self._peak_equity > 0):"),
    ("EXIT NaN drawdown passes silently", "src/qat/risk/gate.py",
     "if not math.isfinite(drawdown):", "if False:"),
    ("EXIT NaN daily loss passes silently", "src/qat/risk/gate.py",
     "if not math.isfinite(loss):", "if False:"),
    ("EXIT relaxation granted on untrusted accounting", "src/qat/risk/gate.py",
     "relax = reducing and not problems", "relax = reducing"),
    ("EXIT breach allows exit despite reconciliation mismatch", "src/qat/risk/gate.py",
     "if recon is not None and not recon[\"ok\"]:", "if False:"),
    ("EXIT breach allows exit despite accounting problems", "src/qat/risk/gate.py",
     "        if problems:\n            return GateDecision(\n                GateStatus.BLOCK,\n                (f\"reservation_breach:{count}:accounting_untrusted:",
     "        if False:\n            return GateDecision(\n                GateStatus.BLOCK,\n                (f\"reservation_breach:{count}:accounting_untrusted:"),
    ("EXIT breach ignores never-reconciled under require_reconciliation", "src/qat/risk/gate.py",
     "if recon is None and self.require_reconciliation:", "if False:"),
    ("EXIT breach exit without authoritative valuation", "src/qat/risk/gate.py",
     "equity = ledger.equity_in(self.base_currency, self.fx_provider, self._marks())", "equity = 0.0"),
    ("EXIT breach that is not an overrun still allowed", "src/qat/risk/gate.py",
     "if any(b.get(\"kind\") != \"reservation_overrun\" for b in ledger.reservation_breaches):", "if False:"),
    ("EXIT breach blocks reducing SELL even when overrun is benign", "src/qat/risk/gate.py",
     "        if not reducing:\n            return GateDecision(GateStatus.BLOCK, (f\"reservation_breach:{count}\",))",
     "        if True:\n            return GateDecision(GateStatus.BLOCK, (f\"reservation_breach:{count}\",))"),
    ("EXIT order notional limit bypassed by reducing SELL", "src/qat/risk/gate.py",
     "if self.max_order_notional is not None and notional > self.max_order_notional:",
     "if self.max_order_notional is not None and notional > self.max_order_notional and not reduces_exposure(self.ledger, proposal):"),
    ("EXIT client supplied reduce flag trusted", "src/qat/core/exposure.py",
     "    if ledger is None:\n        return False\n    position",
     "    if getattr(proposal, \"reduce_only\", False):\n        return True\n    if ledger is None:\n        return False\n    position"),
    ("EXIT settlement mismatch not recorded as integrity issue", "src/qat/execution/settlement.py",
     "self.ledger.record_integrity_issue(\"fill_order_mismatch\",", "(lambda *a, **k: None)(\"fill_order_mismatch\","),
    ("EXIT integrity resolution without clean reconciliation", "src/qat/portfolio/ledger.py",
     "            raise LedgerError(\"integrity resolution requires a clean reconciliation result\")", "            pass"),
    ("EXIT reconciliation result not recorded for Risk", "src/qat/portfolio/reconciliation.py",
     "    ledger.record_reconciliation(ok, reasons)", "    pass"),
    # ---- Batch #3A rebuild: real-data layer ----
    ("DATA raw hash bypass (verify_artifact sha)", "src/qat/realdata/provenance.py",
     'if sha256_bytes(data) != sidecar["sha256"]:', "if False:", RD_ALL),
    ("DATA raw size check bypass", "src/qat/realdata/provenance.py",
     'if len(data) != sidecar["size_bytes"]:', "if False:", RD_ALL),
    ("DATA raw immutability bypass (store_raw overwrite)", "src/qat/realdata/provenance.py",
     "if sha256_bytes(path.read_bytes()) != digest:", "if False:", RD_ALL),
    ("DATA synthetic falsification (provenance accepts synthetic)", "src/qat/realdata/provenance.py",
     'if sidecar["synthetic"] is not False:', "if False:", RD_ALL),
    ("DATA synthetic falsification (V15 ignores dataset flag)", "src/qat/realdata/validate.py",
     "if ctx.synthetic_flag:", "if False:", RD_ALL),
    ("DATA synthetic falsification (admission ignores flag)", "src/qat/realdata/admission.py",
     'if meta.synthetic or identity.get("synthetic") is not False:', "if False:", RD_ALL),
    ("DATA source metadata bypass (V14 raw provider)", "src/qat/realdata/validate.py",
     'if r.get("provider") != ctx.provider:', "if False:", RD_ALL),
    ("DATA source metadata bypass (V14 dataset source)", "src/qat/realdata/validate.py",
     "if ctx.meta_source is not None and ctx.meta_source != ctx.provider:", "if False:", RD_ALL),
    ("DATA source metadata bypass (admission market/symbol/timezone/provider)", "src/qat/realdata/admission.py",
     "if identity.get(field) != got:", "if False:", RD_ALL),
    ("DATA identity file edit undetected", "src/qat/realdata/admission.py",
     'if hashlib.sha256(identity_bytes).hexdigest() != marker.get("identity_sha256"):', "if False:", RD_ALL),
    ("DATA timezone bypass (V12 label)", "src/qat/realdata/validate.py",
     "if ctx.timezone_label != TZ_LABEL.get(ctx.market):", "if False:", RD_ALL),
    ("DATA adjustment UNKNOWN allowed (V16 passes UNKNOWN)", "src/qat/realdata/validate.py",
     'elif adj["final"] == "UNKNOWN":', "elif False:", RD_ALL),
    ("DATA symbol mismatch allowed (V10 provider symbol)", "src/qat/realdata/validate.py",
     "if expected and reported and not reported <= expected:", "if False:", RD_ALL),
    ("DATA symbol mismatch allowed (V10 raw artifact symbol)", "src/qat/realdata/validate.py",
     "    if wrong_raw:", "    if False:", RD_ALL),
    ("DATA row deletion undetected (admission normalized hash)", "src/qat/realdata/admission.py",
     'if dataset.sha256 != identity.get("normalized_sha256"):', "if False:", RD_ALL),
    ("DATA re-normalization not compared (admission)", "src/qat/realdata/admission.py",
     "if fresh[field] != identity[field]:", "if False:", RD_ALL),
    ("DATA trading-day missing session ignored (V13)", "src/qat/realdata/validate.py",
     'status = "FAIL" if (missing_sessions or extra_dates) else "PASS"', 'status = "PASS"', RD_ALL),
    ("DATA duplicate allowed (V07)", "src/qat/realdata/validate.py",
     '"FAIL" if dups else "PASS"', '"PASS"', RD_ALL),
    ("DATA OHLC corruption allowed (V05)", "src/qat/realdata/validate.py",
     '"FAIL" if viol else "PASS"', '"PASS"', RD_ALL),
    ("DATA FAIL dataset admitted (re-validation not required)", "src/qat/realdata/admission.py",
     'if fresh["validation_status"] != "PASS":', "if False:", RD_ALL),
    ("DATA FAIL dataset reaches research (require_admitted no-op)", "src/qat/realdata/admission.py",
     'if not result["admitted"]:', "if False:", RD_ALL),
    ("DATA backtest skips admission", "src/qat/research/backtest.py",
     "    require_admitted(dataset)  # Batch", "    pass  # Batch", RD_ALL),
    ("DATA walk-forward skips admission", "src/qat/research/walkforward.py",
     "    require_admitted(dataset)\n    fixed_params", "    fixed_params", RD_ALL),
    ("DATA UI maps rejection to 500 (not 409)", "src/qat/ui/service.py",
     "        except DataRejected as exc:\n            raise ConflictError(str(exc)) from exc\n        name = str(payload",
     "        except DataRejected as exc:\n            raise RuntimeError(str(exc)) from exc\n        name = str(payload", RD_ALL),
    ("DATA endpoint serviceKey stored unredacted", "src/qat/realdata/secrets.py",
     "REDACTED if k.lower() in _SECRET_PARAMS else v", "v", RD_ALL),
    ("DATA real provider without identity admitted", "src/qat/realdata/admission.py",
     "    if not marker:\n        return", "    if False:\n        return", RD_ALL),
    # ---- Batch #3A.2: KR research scope ----
    ("COVERAGE pre-2020 / out-of-range request silently accepted", "src/qat/realdata/admission.py",
     "if start < lo or end > hi:", "if False:", RD_ALL),
    ("COVERAGE narrower request silently runs the full dataset", "src/qat/realdata/admission.py",
     "if not allow_subperiod and (start, end) != (lo, hi):", "if False:", RD_ALL),
    ("COVERAGE guard skipped by the research service", "src/qat/ui/service.py",
     "            require_coverage(ds, *period)", "            pass", RD_ALL),
    ("COVERAGE dataset without verified record vouches for any period", "src/qat/realdata/admission.py",
     'if not result["applicable"] or "covered_start" not in result:', "if False:", RD_ALL),
    ("COVERAGE adjustment shown as plain provider-grade UNADJUSTED", "src/qat/realdata/adjustment.py",
     'assurance = f"{final}_EVIDENCE_SUPPORTED"', "assurance = final", RD_ALL),
    ("COVERAGE provider explicit statement claimed available", "src/qat/realdata/adjustment.py",
     '"provider_explicit_statement": "AVAILABLE" if stated else "UNAVAILABLE"', '"provider_explicit_statement": "AVAILABLE"', RD_ALL),
    # ---- Batch #3B: Walk-Forward research protocol ----
    ("PROTO start_bar ignored (common-period folds start at bar 0)", "src/qat/research/walkforward.py",
     "out, start = [], self.start_bar", "out, start = [], 0", PROTO),
    ("PROTO lockbox bars dropped from protocol runs", "src/qat/research/protocol.py",
     "lockbox_bars=lockbox, start_bar=start_bar", "lockbox_bars=0, start_bar=start_bar", PROTO),
    ("PROTO activity criterion bypassed (INSUFFICIENT_ACTIVITY never)", "src/qat/research/protocol.py",
     'elif not criteria["activity"]:', "elif False:", PROTO),
    ("PROTO profitable-after-costs not required", "src/qat/research/protocol.py",
     'elif not criteria["profitable_after_costs"]:', "elif False:", PROTO),
    ("PROTO cost-stress survival not required for PASS", "src/qat/research/protocol.py",
     'elif not (criteria["positive_fold_majority"] and criteria["survives_cost_stress"]):',
     'elif not criteria["positive_fold_majority"]:', PROTO),
    ("PROTO lockbox candidate ignores the passive benchmark", "src/qat/research/protocol.py",
     '"lockbox_candidate": status == "PASS" and criteria["beats_passive"]', '"lockbox_candidate": status == "PASS"', PROTO),
    ("PROTO data identity dropped from run manifests", "src/qat/research/protocol.py",
     '"data_identity": identity, "research_window": window}', '"research_window": window}', PROTO),
    ("PROTO same protocol version may be re-run (extra OOS look)", "src/qat/research/protocol.py",
     'if (out_dir / "summary.json").exists():', "if False:", PROTO),
    ("PROTO sub-period selection allowed on the UI/API path", "src/qat/realdata/admission.py",
     "allow_subperiod: bool = False", "allow_subperiod: bool = True", PROTO + RD_ALL),
    ("PROTO determinism fingerprint insensitive", "src/qat/research/protocol.py",
     "    return _sha(keep)", '    return "constant"', PROTO),
    ("PROTO frozen protocol drift accepted", "src/qat/research/protocol.py",
     '["protocol_sha256"] != proto["protocol_sha256"]:', '["protocol_sha256"] == "never":', PROTO),
    # ---- Batch #3C: research validity foundation ----
    ("VALID trial id ignores the parameter combination", "src/qat/research/trials.py",
     '"params": dict(params), "window"', '"params": {}, "window"', VALID),
    ("VALID trial id ignores the settings (cost) hash", "src/qat/research/trials.py",
     '"selection_metric": selection_metric, "base": base, "settings_sha256": settings_sha}', '"selection_metric": selection_metric, "base": base, "settings_sha256": None}', VALID),
    ("VALID trial id ignores the data identity", "src/qat/research/trials.py",
     '"schema": TRIAL_SCHEMA, "data_version": data_version,', '"schema": TRIAL_SCHEMA, "data_version": "x",', VALID),
    ("VALID re-run overwrites/double counts an existing trial", "src/qat/research/trials.py",
     "        if rec is None:", "        if True:", VALID),
    ("VALID failed evaluations not counted as trials", "src/qat/research/trials.py",
     'for cand in row.get("calibration") or []:', 'for cand in [c for c in row.get("calibration") or [] if c["net_return"] is not None]:', VALID),
    ("VALID live runs do not register their trials", "src/qat/research/walkforward.py",
     "    trials.register(trial_rows, run_id", "    (lambda *a, **k: None)(trial_rows, run_id", VALID),
    ("VALID run manifest drops the trial ids", "src/qat/research/walkforward.py",
     '"trial_ids": [x["trial_id"] for x in trial_rows]}', '"trial_ids": []}', VALID),
    ("VALID VERIFIED cost without a primary source accepted", "src/qat/research/cost_evidence.py",
     'if entry["status"] == "VERIFIED" and not (primary and entry["matches_primary_source"]):', "if False:", VALID),
    ("VALID PLACEHOLDER cost allowed to claim a primary match", "src/qat/research/cost_evidence.py",
     'if entry["status"] in ("PLACEHOLDER", "UNKNOWN") and entry["matches_primary_source"]:', "if False:", VALID),
    ("VALID placeholder commission labelled VERIFIED", "src/qat/research/cost_evidence.py",
     '"commission_rate": _e("PLACEHOLDER", "broker/account specific; no broker is chosen"', '"commission_rate": _e("VERIFIED", "broker/account specific; no broker is chosen"', VALID),
    ("VALID unclassified cost parameter ignored", "src/qat/research/cost_evidence.py",
     "            if entry is None:", "            if False:", VALID),
    ("VALID benchmark audit reads the full bars (Lockbox tail)", "src/qat/research/validity.py",
     "bars = ds.bars[:dev_end]  #", "bars = ds.bars  #", VALID),
    # ---- Batch #3D: BTCUSDT 4h foundation, cost v2 contract, per-trial series ----
    ("INTRA 2026 holdout guard bypassed", "src/qat/realdata/intraday.py",
     "if first >= HOLDOUT_START and not holdout_unlocked():", "if False:", INTRA),
    ("INTRA microstructure fetch guard bypassed", "src/qat/realdata/microstructure.py",
     "    if day >= HOLDOUT_START:", "    if False:", INTRA),
    ("INTRA microsecond timestamps not converted", "src/qat/realdata/intraday.py",
     'unit, ms = "us", int(text) // 1000', 'unit, ms = "us", int(text)', INTRA),
    ("INTRA missing 4h bar ignored (continuity)", "src/qat/realdata/intraday.py",
     '"FAIL" if missing else "PASS"', '"PASS"', INTRA),
    ("INTRA wrong bar interval ignored", "src/qat/realdata/intraday.py",
     '"FAIL" if wrong else "PASS"', '"PASS"', INTRA),
    ("INTRA duplicate 4h bar allowed", "src/qat/realdata/intraday.py",
     '"FAIL" if dups else "PASS"', '"PASS"', INTRA),
    ("INTRA holdout bar inside the data not flagged", "src/qat/realdata/intraday.py",
     '"FAIL" if late else "PASS"', '"PASS"', INTRA),
    ("INTRA checksum mismatch accepted at fetch", "src/qat/realdata/intraday.py",
     'if official["sha256"] != hashlib.sha256(zip_bytes).hexdigest() or official["name"] != name:', "if False:", INTRA),
    ("INTRA preserved checksum tamper undetected", "src/qat/realdata/intraday.py",
     'if official["sha256"] != hashlib.sha256(path.read_bytes()).hexdigest() or official["name"] != path.name:', "if False:", INTRA),
    ("COST historical fee may be VERIFIED", "src/qat/research/cost_evidence.py",
     'if entry["scope"] == "historical" and entry["status"] not in ("HISTORICAL_UNKNOWN", "SCENARIO"):', "if False:", INTRA),
    ("COST HISTORICAL_UNKNOWN may carry a value", "src/qat/research/cost_evidence.py",
     'if entry["status"] == "HISTORICAL_UNKNOWN" and entry["value"] is not None:', "if False:", INTRA),
    ("COST VERIFIED_CURRENT without a primary source", "src/qat/research/cost_evidence.py",
     'if entry["scope"] != "current" or not any(s.get("kind") == "primary" for s in entry["sources"]):', "if False:", INTRA),
    ("SERIES winner-only storage accepted", "src/qat/research/trial_series.py",
     '    store.verify_complete([t["trial_id"] for t in trial_rows])', "    pass", INTRA),
    ("SERIES walk-forward stores only the winner", "src/qat/research/walkforward.py",
     '                sink.append({"params": params, "window": list(train), "equity": res.equity})', "                pass", INTRA),
    ("SERIES benchmark enters at open(start) (one-bar misalignment)", "src/qat/research/trial_series.py",
     "return bars[window[1] - 1].close / bars[window[0] + 1].open - 1", "return bars[window[1] - 1].close / bars[window[0]].open - 1", INTRA),
    ("SERIES benchmark per-bar series misaligned", "src/qat/research/trial_series.py",
     "out = [0.0, bars[a + 1].close / bars[a + 1].open - 1]", "out = [bars[a].close / bars[a].open - 1, bars[a + 1].close / bars[a].close - 1]", INTRA),
    ("SERIES conflicting re-store accepted", "src/qat/research/trial_series.py",
     "if path.read_bytes() != data:", "if False:", INTRA),
    # ---- Batch #3E: Protocol v2 pre-registration ----
    ("PV2 failed parent accidentally admitted", "src/qat/realdata/intraday.py",
     'return "ADMITTED_FULL_PERIOD" if validation_status == "PASS" else PARENT_STATUS_FAIL', 'return "ADMITTED_FULL_PERIOD"', PV2),
    ("PV2 view admitted without rule or PASS", "src/qat/realdata/intraday.py",
     'VIEW_STATUS_ADMITTED if (validation_status == "PASS" and derived_by_rule) else "NOT_ADMITTED"', "VIEW_STATUS_ADMITTED", PV2),
    ("PV2 continuity boundary: shortened bar kept in the segment", "src/qat/realdata/intraday.py",
     'if cur["open_ms"] - prev["open_ms"] != INTERVAL_MS or not is_regular_bar(prev):', 'if cur["open_ms"] - prev["open_ms"] != INTERVAL_MS:', PV2),
    ("PV2 continuity boundary: gap ignored by the segment scan", "src/qat/realdata/intraday.py",
     'if cur["open_ms"] - prev["open_ms"] != INTERVAL_MS or not is_regular_bar(prev):', "if not is_regular_bar(prev):", PV2),
    ("PV2 view rows altered (first row dropped)", "src/qat/realdata/intraday.py",
     "*csv_lines[1 + a:2 + b]", "*csv_lines[2 + a:2 + b]", PV2),
    ("PV2 approval marker no longer required for 2026 values", "src/qat/realdata/intraday.py",
     "return FREEZE_MARKER.exists() and APPROVAL_MARKER.exists()", "return FREEZE_MARKER.exists()", PV2 + INTRA + CLOSE),
    ("PV2 S0 used in parameter selection", "src/qat/research/protocol_v2.py",
     'SELECTION_SCENARIOS = ("S1_low", "S2_mid", "S3_high")', 'SELECTION_SCENARIOS = ("S0_commission_only", "S1_low", "S2_mid", "S3_high")', PV2),
    ("PV2 S0 counted in candidate status", "src/qat/research/protocol_v2.py",
     "    for name in SELECTION_SCENARIOS:", "    for name in SELECTION_SCENARIOS + DIAGNOSTIC_SCENARIOS:", PV2),
    ("PV2 best-case instead of worst-case train ranking", "src/qat/research/protocol_v2.py",
     "worst = None if any(v is None for v in scores) else min(scores)", "worst = None if any(v is None for v in scores) else max(scores)", PV2),
    ("PV2 best-case instead of worst-case candidate status", "src/qat/research/protocol_v2.py",
     "worst = min((r[\"status\"] for r in results.values()), key=STATUS_ORDER.index)", "worst = max((r[\"status\"] for r in results.values()), key=STATUS_ORDER.index)", PV2),
    ("PV2 modification after freeze undetected (code drift)", "src/qat/research/protocol_v2.py",
     '"code_matches_frozen_spec": sha(code_body) == recorded', '"code_matches_frozen_spec": True', PV2),
    ("PV2 re-freeze / overwrite allowed", "src/qat/research/protocol_v2.py",
     'if (out_dir / "protocol_v2.json").exists():', "if False:", PV2),
    ("PV2 development end moved", "src/qat/research/protocol_v2.py",
     'DEVELOPMENT_END = "2025-12-31"', 'DEVELOPMENT_END = "2024-12-31"', PV2),
    ("PV2 holdout start moved", "src/qat/research/protocol_v2.py",
     'HOLDOUT_START, HOLDOUT_END = "2026-01-01", "2026-12-31"', 'HOLDOUT_START, HOLDOUT_END = "2026-07-01", "2026-12-31"', PV2),
    ("PV2 minimum fold requirement dropped", "src/qat/research/protocol_v2.py",
     "MIN_FOLDS = 3", "MIN_FOLDS = 1", PV2),
    # ---- Integrated Protocol v2 development execution + one-shot holdout evaluator ----
    ("RUN2 OOS leakage: train window extended into the OOS block", "src/qat/research/protocol_v2_run.py",
     'cfg = _base_config(settings[scen]["path"], train)', 'cfg = _base_config(settings[scen]["path"], [train[0], test[1]])', RUN2),
    ("RUN2 S0 evaluated and used in train selection", "src/qat/research/protocol_v2_run.py",
     "                for scen in pv.SELECTION_SCENARIOS:", "                for scen in ALL_SCENARIOS:", RUN2),
    ("RUN2 best-case instead of worst-case stitched return", "src/qat/research/protocol_v2_run.py",
     '"worst_stitched_net_return": min(x["stitched_net_return"] for x in sel)', '"worst_stitched_net_return": max(x["stitched_net_return"] for x in sel)', RUN2),
    ("RUN2 evaluated trials not registered", "src/qat/research/protocol_v2_run.py",
     "    if register:", "    if False:", RUN2),
    ("RUN2 per-trial series not stored", "src/qat/research/protocol_v2_run.py",
     "        status = store.put(record)", '        status = "stored"', RUN2),
    ("RUN2 ranking ignores the drawdown tie-break", "src/qat/research/protocol_v2_run.py",
     'c["worst_max_drawdown_abs"], -c["worst_oos_closed_trades"]', "-c[\"worst_oos_closed_trades\"]", RUN2),
    ("RUN2 ranking includes non-PASS candidates", "src/qat/research/protocol_v2_run.py",
     'passing = [c for c in candidates if c["status"] == "PASS"]', "passing = list(candidates)", RUN2),
    ("RUN2 dataset reaching the 2026 holdout not refused", "src/qat/research/protocol_v2_run.py",
     "if dataset.bars[-1].ts.date() >= intraday.HOLDOUT_START and not intraday.holdout_unlocked():", "if False:", RUN2),
    ("RUN2 addendum accepted after a performance run exists", "src/qat/research/protocol_v2_run.py",
     'if evidence["development_run_dir_exists"] or v2_trials or evidence["trial_series_files_for_wf-protocol-2"]:', "if False:", RUN2),
    ("HOLD holdout may be evaluated twice", "src/qat/research/holdout_eval.py",
     'if (out_dir / "attempt.json").exists() or (out_dir / "result.json").exists() or (out_dir / "failure.json").exists():', "if False:", HOLD),
    ("HOLD partial-year evaluation allowed", "src/qat/research/holdout_eval.py",
     "    if missing:", "    if False:", HOLD),
    ("HOLD candidate identity mismatch accepted", "src/qat/research/holdout_eval.py",
     'if not cand_check["ok"]:', "if False:", HOLD),
    ("HOLD approval marker not checked", "src/qat/research/holdout_eval.py",
     'problems += check_approval(approval_path, candidate, add_check["holdout_addendum_sha256"])', "pass", HOLD),
    ("HOLD unverified 2026 data is evaluated anyway", "src/qat/research/holdout_eval.py",
     'if data["validation"]["status"] != "PASS":', "if False:", HOLD),
    ("HOLD final selection window overlaps the evaluation block", "src/qat/research/holdout_eval.py",
     '"train": [n_dev - final_train_bars, n_dev]', '"train": [n_dev - final_train_bars, n_total]', HOLD),
    ("HOLD single-block min_folds override dropped", "src/qat/research/holdout_eval.py",
     "run_id=RUN_ID, min_folds=1)", "run_id=RUN_ID)", HOLD),
    ("RUN2 view admission: dataset bytes not compared", "src/qat/realdata/admission.py",
     'if dataset.sha256 != identity.get("view_normalized_sha256"):', "if False:", RUN2),
    ("RUN2 view admission: fresh derivation not required to reproduce", "src/qat/realdata/admission.py",
     "if intraday.identity_bytes(fresh[\"identity\"]) != identity_bytes:", "if False:", RUN2),
    ("RUN2 view admission: synthetic flag ignored", "src/qat/realdata/admission.py",
     'if meta.synthetic is not False or identity.get("synthetic") is not False:', "if False:", RUN2),
    # ---- Protocol v2 closure: frozen eligibility cannot be bypassed ----
    ("CLOSE closed protocol still unlocks 2026 values", "src/qat/realdata/intraday.py",
     "if CLOSURE_MARKER.exists():", "if False:", CLOSE),
    ("CLOSE approval can bypass frozen eligibility (check_approval)", "src/qat/research/holdout_eval.py",
     'if candidate["holdout_eligible_by_frozen_rule"] is not True:', "if False:", CLOSE),
    ("CLOSE evaluator ignores the candidate eligibility flag", "src/qat/research/holdout_eval.py",
     'if candidate_header.get("holdout_eligible_by_frozen_rule") is not True:', "if False:", CLOSE),
    ("CLOSE evaluator ignores the protocol closure record", "src/qat/research/holdout_eval.py",
     "if closure.exists() and json.loads(", "if False and json.loads(", CLOSE),
    ("CLOSE benchmark eligibility passes if any scenario beats passive", "src/qat/research/protocol_v2_closure.py",
     '"status": "PASS" if all(v["exceeds_aligned_passive"] for v in per.values()) else "FAIL"', '"status": "PASS" if any(v["exceeds_aligned_passive"] for v in per.values()) else "FAIL"', CLOSE),
    ("CLOSE closure verification ignores the holdout lock", "src/qat/research/protocol_v2_closure.py",
     '"holdout_locked": intraday.holdout_unlocked() is False,', '"holdout_locked": True,', CLOSE),
    # ---- QAT v1 final completion: stale snapshot / durable audit / recovery / broker boundary / graduation / Live ----
    ("OPS stale snapshot treated as fresh by the risk gate", "src/qat/risk/gate.py",
     "if fr_status is Freshness.FRESH:", "if fr_status is not Freshness.UNKNOWN:", OPSC),
    ("OPS freshness never reports STALE", "src/qat/ops/snapshot.py",
     "if age > max_age_seconds:", "if False:", OPSC),
    ("OPS stale snapshot attests reconciliation", "src/qat/ops/snapshot.py",
     "if fr.status is not Freshness.FRESH:", "if False:", OPSC),
    ("OPS missing snapshot timestamp counts as fresh", "src/qat/ops/snapshot.py",
     'return unknown("snapshot_timestamp_missing")', 'return FreshnessResult(Freshness.FRESH, 0.0, 0.0, max_age_seconds, "x")', OPSC),
    ("OPS stale snapshot exit allowed on untrusted books", "src/qat/risk/gate.py",
     "if reducing and books_trusted:", "if reducing:", OPSC),
    ("OPS market rules block exits too (relax dropped)", "src/qat/risk/gate.py",
     "            if relax:\n                notes.append(f\"exit_allowed:{rule}:{reason}\")", "            if False:\n                notes.append(f\"exit_allowed:{rule}:{reason}\")", OPSC),
    ("OPS market rules never block new risk (relax always)", "src/qat/risk/gate.py",
     "            if relax:\n                notes.append(f\"exit_allowed:{rule}:{reason}\")", "            if True:\n                notes.append(f\"exit_allowed:{rule}:{reason}\")", OPSC),
    ("OPS R-07 minimum volume ignored", "src/qat/ops/market_rules.py",
     "if ctx.volume <= 0 or ctx.volume < min_bar_volume:", "if ctx.volume <= 0:", OPSC),
    ("OPS R-08 missing quotes treated as PASS", "src/qat/ops/market_rules.py",
     'return UNKNOWN, "spread_unavailable:no_quote_data"', 'return PASS, "x"', OPSC),
    ("OPS R-09 volatility shock never blocks", "src/qat/ops/market_rules.py",
     "if rng > range_pct_limit:", "if False:", OPSC),
    ("OPS MI-06 participation never blocks", "src/qat/ops/market_rules.py",
     "if rate > max_rate:", "if False:", OPSC),
    ("OPS MI-05 cancel pattern never blocks", "src/qat/ops/market_rules.py",
     "if recent > max_cancels:", "if False:", OPSC),
    ("OPS audit hash chain does not link records", "src/qat/ops/audit_store.py",
     'body = {"seq": self._seq + 1, "prev_hash": self._last_hash,', 'body = {"seq": self._seq + 1, "prev_hash": GENESIS,', OPSC),
    ("OPS audit append is not fsynced", "src/qat/ops/audit_store.py",
     "os.fsync(handle.fileno())", "pass", OPSC),
    ("OPS audit verify ignores tampered records", "src/qat/ops/audit_store.py",
     'if _hash(rec["prev_hash"], body) != rec["hash"]:', "if False:", OPSC),
    ("OPS audit idempotency conflict is swallowed", "src/qat/ops/audit_store.py",
     'if self._content[clean["event_id"]] == content_hash:', "if True:", OPSC),
    ("OPS audit does not scrub secret-looking keys", "src/qat/ops/audit_store.py",
     "REDACTED if _SECRET_KEY.search(str(k)) else scrub(v)", "scrub(v)", OPSC),
    ("OPS audit does not scrub secret-looking values", "src/qat/ops/audit_store.py",
     "_SECRET_VALUE.sub(lambda m: m.group(1) + REDACTED, obj) if isinstance(obj, str) else obj", "obj", OPSC),
    ("OPS corrupt state file read as default (silent reset)", "src/qat/ops/atomic.py",
     'raise StateCorrupt(f"{path.name}: {type(exc).__name__}: {exc}") from exc', "return default", OPSC),
    ("OPS strategy health ignores stale data", "src/qat/ops/strategy_health.py",
     'elif self.last_data_ts is not None and (now - self.last_data_ts).total_seconds() > t["max_data_age_seconds"]:', "elif False:", OPSC),
    ("OPS strategy health treats no-trade as a failure", "src/qat/ops/strategy_health.py",
     'r.notes.append("no signals/trades so far: not a failure (a quiet strategy is healthy)")', 'raise_to(DEGRADED, "no_trades")', OPSC),
    ("OPS ops config accepts non-finite thresholds", "src/qat/ops/config.py",
     "or not math.isfinite(value):", "or False:", OPSC),
    ("OPS corrupt research registry read as empty", "src/qat/research/store.py",
     "return read_json_strict(_registry(name), default={})", "return {}", OPSC),
    ("OPS unauthenticated recovery token accepted", "src/qat/core/recovery.py",
     "bool(self.token) and self.token in _ISSUED_TOKENS and", "True and", OPSS),
    ("OPS flatten order may increase exposure", "src/qat/core/orchestrator.py",
     "if not reduces_exposure(ledger, proposal):", "if False:", OPSS),
    ("OPS flatten skips the accounting-integrity check", "src/qat/core/orchestrator.py",
     "            if problems:\n                return refuse(\"accounting_untrusted\", problems[:3])", "            if False:\n                return refuse(\"accounting_untrusted\", problems[:3])", OPSS),
    ("OPS flatten ignores a reconciliation mismatch", "src/qat/ops/recovery.py",
     'blockers.append("reconciliation_mismatch")', "pass", OPSS),
    ("OPS flatten needs no literal confirmation", "src/qat/ops/recovery.py",
     "if confirm != CONFIRM_TOKEN:", "if False:", OPSS),
    ("OPS flatten replay is not idempotent", "src/qat/ops/recovery.py",
     'if flat and flat.get("session_uid") == self.session_uid and flat.get("orders"):', "if False:", OPSS),
    ("OPS flatten sells more than held", "src/qat/ops/recovery.py",
     "quantity=pos.available_quantity,", "quantity=pos.quantity * 2,", OPSS),
    ("OPS restart assessment ignores unknown pending orders", "src/qat/ops/recovery.py",
     'if prev.get("pending_orders") and not prev.get("clean_shutdown"):', "if False:", OPSS),
    ("OPS recovery-required state does not block new risk", "src/qat/ui/service.py",
     'if rec.get("status") in ("RECOVERY_REQUIRED", "FLATTEN_SUBMITTED"):', "if False:", OPSS),
    ("OPS audit FAULT does not stop trading", "src/qat/ui/service.py",
     "if not self.audit_store.healthy:", "if False:", OPSS),
    ("OPS corrupt latch file silently reset", "src/qat/ui/service.py",
     "return self._quarantine(exc)", 'return {"active": [], "cleared": []}', OPSS),
    ("OPS flatten accepts client-supplied fields", "src/qat/ui/service.py",
     'unknown = set(payload) - {"operator", "reason", "confirm"}',
     'unknown = set(payload) - {"operator", "reason", "confirm", "quantity", "price", "side", "approved", "status", "symbol", "authorization", "flatten_available", "state", "kill_switch"}', OPSS),
    ("OPS audit view serves a corrupt log", "src/qat/ui/service.py",
     'if not verify["ok"]:\n            return {**base, "total": 0,', 'if False:\n            return {**base, "total": 0,', OPSS),
    ("OPS startup ignores audit chain failure", "src/qat/ops/startup.py",
     'checks.append(_check("audit_chain", PASS if report["ok"] else BLOCK,', 'checks.append(_check("audit_chain", PASS,', OPSS),
    ("OPS startup does not refuse Live configuration", "src/qat/ops/startup.py",
     "if live_reasons:", "if False:", OPSS),
    ("OPS startup BLOCK does not stop trading", "src/qat/ui/service.py",
     'if self.startup["status"] == "BLOCK":', "if False:", OPSS),
    ("OPS repeated audit query parameters accepted", "src/qat/ui/server.py",
     "if any(len(v) != 1 for v in parsed.values()):", "if False:", OPSS),
    ("OPS health reports NOT_CONFIGURED as overall pass", "src/qat/ops/health.py",
     "overall = worst if worst != NOT_CONFIGURED else DEGRADED", "overall = PASS if worst == NOT_CONFIGURED else worst", OPSS),
    ("OPS health maps missing reconciliation to PASS", "src/qat/ops/health.py",
     '.get(recon.get("status"), UNKNOWN)', '.get(recon.get("status"), PASS)', OPSS),
    ("OPS graduation: hard blocker never BLOCKED", "src/qat/ops/graduation.py",
     'if any(g["hard"] and g["status"] == FAIL for g in gates):', "if False:", OPSS),
    ("OPS graduation: failed gate does not deny", "src/qat/ops/graduation.py",
     'elif any(g["status"] == FAIL for g in gates):', "elif False:", OPSS),
    ("OPS graduation: UNKNOWN gate graduates (false PASS)", "src/qat/ops/graduation.py",
     'elif any(g["status"] == "UNKNOWN" for g in gates):', "elif False:", OPSS),
    ("OPS graduation ignores Protocol v2 NOT_HOLDOUT_ELIGIBLE", "src/qat/ops/graduation.py",
     'elif "NOT_HOLDOUT_ELIGIBLE" in research_label or "CLOSED" in research_label:', "elif False:", OPSS),
    ("OPS graduation ignores too few paper sessions", "src/qat/ops/graduation.py",
     'OK if len(done) >= need else FAIL', "OK", OPSS),
    ("OPS Live readiness can unblock", "src/qat/ops/graduation.py",
     'return {"status": "BLOCKED", "blockers": blockers,', 'return {"status": "BLOCKED" if blockers[1:] else "READY", "blockers": blockers,', OPSS),
    ("BRK unknown submit state is dropped (treated as success)", "src/qat/brokerage/boundary.py",
     '            self._mark_unknown(order, f"{exc.kind}_during_submit")\n            if isinstance(exc, BrokerConnectionLost):',
     '            if isinstance(exc, BrokerConnectionLost):', BRK),
    ("BRK UNKNOWN status becomes terminal/cleared", "src/qat/brokerage/boundary.py",
     'self.unknown_orders[order.order_id] = reason or "unknown"', "self.unknown_orders.pop(order.order_id, None)", BRK),
    ("BRK duplicate fill callback applied twice", "src/qat/brokerage/boundary.py",
     "if report.broker_fill_id in self.seen_fill_ids:", "if False:", BRK),
    ("BRK overfill accepted", "src/qat/brokerage/boundary.py",
     "if report.quantity - order.remaining_quantity > _EPS:", "if False:", BRK),
    ("BRK fill for another side accepted", "src/qat/brokerage/boundary.py",
     "if side is not order.side:", "if False:", BRK),
    ("BRK new exposure allowed while broker state unverified", "src/qat/brokerage/boundary.py",
     "if (self.unknown_orders or self.needs_reconciliation or not self.connected) and not reduces_exposure(", "if False and not reduces_exposure(", BRK),
    ("BRK reconnect does not invalidate reconciliation", "src/qat/brokerage/boundary.py",
     'self._ledger.record_reconciliation(False, ["reconnect_requires_reconciliation"])', "pass", BRK),
    ("BRK snapshot failure leaves reconciliation untouched", "src/qat/brokerage/boundary.py",
     'self._ledger.record_reconciliation(False, [f"snapshot_unavailable:{exc.kind}"])', "pass", BRK),
    ("BRK unconfirmed cancel releases the reservation", "src/qat/brokerage/boundary.py",
     'raise  # still CANCEL_PENDING (not terminal); SettlementService.cancel therefore does NOT release the reservation', 'return order', BRK),
]


def main() -> int:
    return mutation_harness.run_all(MUTS, root=ROOT, tests=TESTS, only=sys.argv[1:], python=PY)


if __name__ == "__main__":
    raise SystemExit(main())
